name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1 ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        base_href: /angular-example-starter/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: main # The branch the action should deploy to.
        angular_dist_build_folder: dist/angular-example-starter # The folder where your project is supposed to be after running ng build by the action.

# name: "build-test"
# on: # rebuild any PRs and main branch changes
#   pull_request:
#   push:
#     branches:
#       - master
#       - 'releases/*'

# jobs:
#   build_and_test_action: # make sure build/ci work properly
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - run: |
#         npm install
#         npm run all
#   test_demo_app: # run the demo app's unit tests
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - run: |
#         npm install
#         npm run test:ci
#       working-directory: './angular-example-starter'
#   test_action_and_deploy_demo: # make sure the action works on a clean machine without building
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: 'Deploy demo app using action'
#       uses: ./
#       with:
#         run_lint: true
#         github_access_token: ${{ secrets.ACCESS_TOKEN }}
#         build_configuration: master
#         base_href: /angular-example-starter/
#         deploy_branch: gh-pages # The branch the action should deploy to.
#         angular_dist_build_folder: online6731/dist/angular-example-starter # The folder the action should deploy.
#         angular_project_dir: angular-example-starter
